### ISSUE TITLE
SARIMAX prediction LinAlgError: Non-positive definite forecast

### ISSUE THREAD

**Issue by Kalelv45** [notadamking/Bitcoin-Trader-RL#14]
[W 2019-06-07 12:02:31,288] Setting status of trial#6 as TrialState.FAIL because of the following error: LinAlgError('Non-positive-definite forecast error covariance matrix encountered at period 1')
Traceback (most recent call last):
  File "_inversions.pyx", line 1107, in statsmodels.tsa.statespace._filters._inversions.zinverse_univariate
ZeroDivisionError: float division

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/optuna/study.py", line 399, in _run_trial
    result = func(trial)
  File "./optimize.py", line 80, in optimize_agent
    model.learn(evaluation_interval)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 277, in learn
    runner = Runner(env=self.env, model=self, n_steps=self.n_steps, gamma=self.gamma, lam=self.lam)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 399, in __init__
    super().__init__(env=env, model=model, n_steps=n_steps)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines/common/runners.py", line 19, in __init__
    self.obs[:] = env.reset()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 45, in reset
    obs = self.envs[env_idx].reset()
  File "/Users/XXXX/Downloads/Bitcoin-Trader-RL-master/env/BitcoinTradingEnv.py", line 182, in reset
    return self._next_observation()
  File "/Users/XXXX/Downloads/Bitcoin-Trader-RL-master/env/BitcoinTradingEnv.py", line 81, in _next_observation
    model_fit = forecast_model.fit(method='bfgs', disp=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 469, in fit
    skip_hessian=True, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/base/model.py", line 466, in fit
    full_output=full_output)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 191, in _fit
    hess=hessian)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 327, in _fit_bfgs
    disp=disp, retall=retall, callback=callback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 942, in fmin_bfgs
    res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 996, in _minimize_bfgs
    gfk = myfprime(x0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 326, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/base/model.py", line 451, in score
    return -self.score(params, *args) / nobs
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 1077, in score
    score = self._score_complex_step(params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 944, in _score_complex_step
    kwargs=kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tools/numdiff.py", line 202, in approx_fprime_cs
    for i, ih in enumerate(increments)]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tools/numdiff.py", line 202, in <listcomp>
    for i, ih in enumerate(increments)]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 646, in loglike
    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 825, in loglike
    kfilter = self._filter(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 750, in _filter
    kfilter()
  File "_kalman_filter.pyx", line 3632, in statsmodels.tsa.statespace._kalman_filter.zKalmanFilter.__call__
  File "_kalman_filter.pyx", line 3698, in statsmodels.tsa.statespace._kalman_filter.zKalmanFilter.__next__
  File "_inversions.pyx", line 1109, in statsmodels.tsa.statespace._filters._inversions.zinverse_univariate
numpy.linalg.LinAlgError: Non-positive-definite forecast error covariance matrix encountered at period 1

**Comment by notadamking** [comment]
This is "normal", as in I have also run into this. However, it causes trials to fail unnecessarily, which is not ideal. I have spent a bit of time debugging this specific error, and have not been able to find a solution. Has anyone else had any success?

**Comment by notadamking** [comment]
The error seems to be caused by a divide-by-zero (ZeroDivisionError: float division) within the SARIMAX.fit() function, though I am unsure how to prevent it currently.

**Comment by JohnAllen** [comment]
I found [this issue](https://github.com/statsmodels/statsmodels/issues/5374#issuecomment-438261637) that seems to be about the same issue (I also get it).  

Possibly adding: `simple_differencing=True` where SARIMAX is called [at this line here](https://github.com/notadamking/Bitcoin-Trader-RL/blob/master/env/BitcoinTradingEnv.py#L80) will solve this. 

Will try it myself and report if it prevents this error or not.

**Comment by notadamking** [comment]
Great, I'd love to hear your results.

**Comment by JohnAllen** [comment]
Think that works.  I ran optimize.py for a while and didn't get that error again.

**Comment by notadamking** [comment]
Great, I will add the change to the repo and get it pushed.

**Comment by JohnAllen** [comment]
I was about to submit a PR.  Will and hope you see this.

**Comment by notadamking** [comment]
@JohnAllen thanks, I will wait for your PR!

**Comment by notadamking** [comment]
After running `optimize.py` for a couple hours with `simple_differencing=True`, I have run into the issue again. Unfortunately, this does not seem to have fixed the issue.

**Comment by notadamking** [comment]
The [thread above](https://github.com/statsmodels/statsmodels/issues/5374#issuecomment-438261637) mentions upgrading the `statsmodels` package to version 0.10.0 to fix the issue. I will try this.

**Comment by mpearmain** [comment]
This fix seems to be working for me - upgrading to statsmodel `0.10.0rc2`

**Comment by archenroot** [comment]
Confirm, its gone now...

**Comment by bing007** [comment]
> The [thread above](https://github.com/statsmodels/statsmodels/issues/5374#issuecomment-438261637) mentions upgrading the `statsmodels` package to version 0.10.0rc2 to fix the issue. I will try this.

Run for a couple of hours now, seem to be working

**Comment by rhamnett** [comment]
Just ran into this as a new user. I recommend you change requirements.txt to

statsmodels==0.10.0rc2

**Comment by notadamking** [comment]
Glad to hear this fixed the issue for everyone. Pushed [the fix](https://github.com/notadamking/Bitcoin-Trader-RL/commit/595693e78e71f7eaf14ff24590668b85f0881253)
