### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by archenroot** [notadamking/Bitcoin-Trader-RL#20]
While on 32 thread system I set numpy task from 4 to 32 and started getting:
```
[W 2019-06-08 15:21:37,332] Setting status of trial#10 as TrialState.FAIL because of the following error: OperationalError('(sqlite3.OperationalError) database is locked',)
Traceback (most recent call last):
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/study.py", line 399, in _run_trial
    result = func(trial)
  File "optimize.py", line 79, in optimize_agent
    model_params = optimize_ppo2(trial)
  File "optimize.py", line 62, in optimize_ppo2
    'n_steps': int(trial.suggest_loguniform('n_steps', 16, 2048)),
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/trial.py", line 207, in suggest_loguniform
    return self._suggest(name, distribution)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/trial.py", line 440, in _suggest
    distribution)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/samplers/tpe/sampler.py", line 73, in sample
    observation_pairs = storage.get_trial_param_result_pairs(study_id, param_name)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/storages/base.py", line 209, in get_trial_param_result_pairs
    all_trials = self.get_all_trials(study_id)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/storages/rdb/storage.py", line 497, in get_all_trials
    trials = self._get_all_trials_without_cache(study_id)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/storages/rdb/storage.py", line 519, in _get_all_trials_without_cache
    study = models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/storages/rdb/models.py", line 56, in find_or_raise_by_id
    study = cls.find_by_id(study_id, session)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/optuna/storages/rdb/models.py", line 48, in find_by_id
    study = session.query(cls).filter(cls.study_id == study_id).one_or_none()
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3323, in __iter__
    return self._execute_and_instances(context)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3348, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/zangetsu/proj/prometheus-core/demo/demo-12-bitcoin-trading-agent/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT studies.study_id AS studies_study_id, studies.study_name AS studies_study_name, studies.direction AS studies_direction 
FROM studies 
WHERE studies.study_id = ?]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

```

Its because of the sqlite limited concurency:

> SQLite is meant to be a lightweight database, and thus can't support a high level of concurrency. OperationalError: database is locked errors indicate that your application is experiencing more concurrency than sqlite can handle in default configuration. This error means that one thread or process has an exclusive lock on the database connection and another thread timed out waiting for the lock the be released.
> 
> Python's SQLite wrapper has a default timeout value that determines how long the second thread is allowed to wait on the lock before it times out and raises the OperationalError: database is locked error.
> 
> If you're getting this error, you can solve it by:
> 
> Switching to another database backend. At a certain point SQLite becomes too "lite" for real-world applications, and these sorts of concurrency errors indicate you've reached that point.
> 
> Rewriting your code to reduce concurrency and ensure that database transactions are short-lived.
> 
> Increase the default timeout value by setting the timeout database option.

So I created local instance of Postgresql:
```
create database hyperparamdb;
create user hyperparamdb with encrypted password 'hyperparamdb';
grant all privileges on database hyperparamdb to hyperparamdb;

postgresql://hyperparamdb:hyperparamdb@localhost/hyperparamdb


CREATE ROLE zangetsu SUPERUSER;
ALTER ROLE "zangetsu" WITH LOGIN;
```
And I configured optane with new URL everywhere:
`params_db_file = 'postgresql://hyperparamdb:hyperparamdb@localhost/hyperparamdb'`

Postgres handle quite nicely this, so it works on 40 tasks now.

**Comment by archenroot** [comment]
Ok, with postgres I have now other issue:
`sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached` I am looking for some db url param to pass to extend this if possible.

**Comment by archenroot** [comment]
Ok, this is not jdbc, but sqlalchemy, so:
`params_db_file = 'postgresql://hyperparamdb:hyperparamdb@localhost/hyperparamdb?pool_size=200&pool_timeout=8000'`

**Comment by archenroot** [comment]
no, it doesn't work... looks like pool_size must go vie conn_args and is not recognized via url string....

**Comment by archenroot** [comment]
I am still not sure if I do something wrong, but I reported to SQL alchemy and will wait what they say:
[](https://github.com/sqlalchemy/sqlalchemy/issues/4714)

Otherwise even when set to 12 jobs, sqlite is failin on locked db...

**Comment by archenroot** [comment]
It looks optuna doesn't support passing custom args for db driver, I raised a ticket upstream to support this.

**Comment by notadamking** [comment]
Unfortunately, I have run into this error as well and it seems to be a problem in SQLite or SQL Alchemy. That being said, Optuna does have some documentation on replacing the SQLite storage with another RDB backend.

https://optuna.readthedocs.io/en/stable/tutorial/rdb.html#rdb

**Comment by archenroot** [comment]
@notadamking - I did it, I tested with Postgres, but when I set n_jobs from initial 4 to 40, it failes on both sqllite and postgres. On postgres we need to pass down to optuna some driver settings, but their api doesn;'t support it (yet) i did a request:
https://github.com/pfnet/optuna/issues/423

When don, we can get some more power with more jobs running in parallel.

**Comment by archenroot** [comment]
Ok, so we have some progress, op tuna will finally support a RDBMS connection parameters to be passed via kwargs: https://github.com/pfnet/optuna/pull/425

This of course open a capability to run parallel optuna tasks with single database as central store of best trials...
