### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ./tensorboard\PPO2_1; No such file or directory

### ISSUE THREAD

**Issue by joanmassana** [notadamking/Bitcoin-Trader-RL#33]
Hi. I am trying to get the whole thing to work. It's my first time using Python and Tensorflow so I apologize if this is a rookie mistake :) .
Issue is when I run `python ./optimize.py` I get the following error for each trial.

```
[W 2019-06-11 18:55:51,636] Setting status of trial#13 as TrialState.FAIL because of the following error: NotFoundError()
Traceback (most recent call last):
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\optuna\study.py", line 399, in _run_trial
    result = func(trial)
  File "./optimize.py", line 88, in optimize_agent
    model.learn(evaluation_interval)
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\stable_baselines\ppo2\ppo2.py", line 273, in learn
    with SetVerbosity(self.verbose), TensorboardWriter(self.graph, self.tensorboard_log, tb_log_name, new_tb_log) \
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\stable_baselines\common\base_class.py", line 693, in __enter__
    self.writer = tf.summary.FileWriter(save_path, graph=self.graph)
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\summary\writer\writer.py", line 367, in __init__
    filename_suffix)
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\summary\writer\event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "C:\Users\Projects\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ./tensorboard\PPO2_1; No such file or directory```

**Comment by stefintrim** [comment]
This is a Windows path issue - see PR #32
 "fix issue with file path forward slash in Windows"

**Comment by notadamking** [comment]
Can anyone confirm that #32 fixes this issue?

**Comment by joanmassana** [comment]
I'm checking if this works for me. Thanks for the feedback.
