### ISSUE TITLE
TensorFlow Fail

### ISSUE THREAD

**Issue by JakubSledz** [notadamking/Bitcoin-Trader-RL#37]
After resolving all the issues with requirements and tensorflow I have this error afte running opthymize.pi

(C:\Users\USER-KIN-00381\Anaconda3\envs\crypt) D:\BTR>python ./optimize.py
[I 2019-06-12 15:42:39,174] A new study created with name: ppo2_sortino
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\common\policies.py:420: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\ops\math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
[W 2019-06-12 15:44:03,396] Setting status of trial#2 as TrialState.FAIL because of the following error: NotFoundError()
Traceback (most recent call last):
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\optuna\study.py", line 399, in _run_trial
    result = func(trial)
  File "./optimize.py", line 89, in optimize_agent
    model.learn(evaluation_interval)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 273, in learn
    with SetVerbosity(self.verbose), TensorboardWriter(self.graph, self.tensorboard_log, tb_log_name, new_tb_log) \
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\common\base_class.py", line 693, in __enter__
    self.writer = tf.summary.FileWriter(save_path, graph=self.graph)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\summary\writer\writer.py", line 367, in __init__
    filename_suffix)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\summary\writer\event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ./tensorboard\PPO2_1; No such file or directory
[W 2019-06-12 15:44:32,769] Setting status of trial#1 as TrialState.FAIL because of the following error: NotFoundError()
Traceback (most recent call last):
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\optuna\study.py", line 399, in _run_trial
    result = func(trial)
  File "./optimize.py", line 89, in optimize_agent
    model.learn(evaluation_interval)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 273, in learn
    with SetVerbosity(self.verbose), TensorboardWriter(self.graph, self.tensorboard_log, tb_log_name, new_tb_log) \
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\common\base_class.py", line 693, in __enter__
    self.writer = tf.summary.FileWriter(save_path, graph=self.graph)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\summary\writer\writer.py", line 367, in __init__
    filename_suffix)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\summary\writer\event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ./tensorboard\PPO2_1; No such file or directory

**Comment by joanmassana** [comment]
Had the same problem. It is related to this issue: #32 .

**Comment by JakubSledz** [comment]
Thanks

**Comment by JakubSledz** [comment]
Now I get this:
[I 2019-06-12 16:25:43,784] A new study created with name: ppo2_sortino
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\common\policies.py:420: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\ops\math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.

**Comment by moxis** [comment]
> Now I get this:
> [I 2019-06-12 16:25:43,784] A new study created with name: ppo2_sortino
> WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\common\policies.py:420: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.flatten instead.
> WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.cast instead.
> WARNING:tensorflow:From C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\tensorflow\python\ops\math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Deprecated in favor of operator or tf.math.divide.

Those are just warnings. It should still run normally without issues now.

**Comment by JakubSledz** [comment]
And what feeddback I will get and when that there is actually something happening? ;) Sorry for noob question

**Comment by silentrob** [comment]
You should see hear your CPU fan kick in and eventually see the output in the console like "Trial #1 ..." This will go to 1000 or until you cancel it several days later :)

**Comment by JakubSledz** [comment]
> You should hear your CPU fan kick in and eventually see the output in the console like "Trial #1 ..." This will go to 1000 or until you cancel it several days later :)

I thought it should be GPU ;) Thanks for the repk

**Comment by TalhaAsmal** [comment]
> > You should hear your CPU fan kick in and eventually see the output in the console like "Trial #1 ..." This will go to 1000 or until you cancel it several days later :)
> 
> I thought it should be GPU ;) Thanks for the repk

The GPU is still heavily underutilized. See #10 for more info
