### ISSUE TITLE
ImportError: numpy.core._multiarray_umath failed to import ImportError: numpy.core.umath failed to import

### ISSUE THREAD

**Issue by nachovoss** [notadamking/Bitcoin-Trader-RL#44]
Hey guys! 
i'm getting the following error when trying to run optimize.py and training.py.

Have someone encountered similar issues?
help will be much appreciated.

thanks in advance

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-06-14 15:02:55.452026: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

(base) C:\Users\Nacho\Desktop\bots\Bitcoin-Trader-RL>python train.py
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-06-14 15:09:29.405024: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

**Comment by nachovoss** [comment]
Fixed by installing pip install numpy --upgrade and  pip install --upgrade scikit-image on the conda environment, but now i get a new error:

Traceback (most recent call last):
  File "./optimize.py", line 16, in <module>
    from stable_baselines.common.policies import MlpLnLstmPolicy
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\__init__.py", line 4, in <module>
    from stable_baselines.ddpg import DDPG
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ddpg\__init__.py", line 1, in <module>
    from stable_baselines.ddpg.ddpg import DDPG
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ddpg\ddpg.py", line 12, in <module>
    from mpi4py import MPI
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

**Comment by nachovoss** [comment]
fixed by installing Microsoft MPI https://www.microsoft.com/en-us/download/details.aspx?id=57467


buy now i get a new error...:
python ./train.py
Traceback (most recent call last):
  File "./train.py", line 22, in <module>
    study = optuna.load_study(study_name=study_name, storage=params_db_file)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\optuna\study.py", line 557, in load_study
    return Study(study_name=study_name, storage=storage, sampler=sampler, pruner=pruner)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\optuna\study.py", line 78, in __init__
    self.study_id = self.storage.get_study_id_from_name(study_name)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\optuna\storages\rdb\storage.py", line 165, in get_study_id_from_name
    study = models.StudyModel.find_or_raise_by_name(study_name, session)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\optuna\storages\rdb\models.py", line 76, in find_or_raise_by_name
    raise ValueError(NOT_FOUND_MSG)
ValueError: Record does not exist.

**Comment by nachovoss** [comment]
fixed by upgrading pandas 'pip install -- upgrade pandas' in   conda base
