### ISSUE TITLE
optimize error

### ISSUE THREAD

**Issue by nachovoss** [notadamking/Bitcoin-Trader-RL#46]
hey guys!
When runnng the optimizer i get the following error:
any ideas?

[I 2019-06-14 15:34:12,654] A new study created with name: ppo2_sortino
WARNING:tensorflow:From C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\policies.py:420: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
[I 2019-06-14 17:27:07,947] Finished trial#1 resulted in value: -19551.509765625. Current best value is -19551.509765625 with parameters: {'cliprange': 0.38113219124165043, 'confidence_interval': 0.8556293119927123, 'ent_coef': 0.00013022093535861756, 'forecast_len': 3.0216790310549677, 'gamma': 0.9299473170995376, 'lam': 0.8620846641431216, 'learning_rate': 0.008580823341236382, 'n_steps': 181.9906757748466, 'noptepochs': 19.321405513375872}.
[I 2019-06-14 17:39:50,201] Finished trial#3 resulted in value: -8186.02001953125. Current best value is -19551.509765625 with parameters: {'cliprange': 0.38113219124165043, 'confidence_interval': 0.8556293119927123, 'ent_coef': 0.00013022093535861756, 'forecast_len': 3.0216790310549677, 'gamma': 0.9299473170995376, 'lam': 0.8620846641431216, 'learning_rate': 0.008580823341236382, 'n_steps': 181.9906757748466, 'noptepochs': 19.321405513375872}.
[I 2019-06-14 17:49:38,959] Finished trial#2 resulted in value: 21770.931640625. Current best value is -19551.509765625 with parameters: {'cliprange': 0.38113219124165043, 'confidence_interval': 0.8556293119927123, 'ent_coef': 0.00013022093535861756, 'forecast_len': 3.0216790310549677, 'gamma': 0.9299473170995376, 'lam': 0.8620846641431216, 'learning_rate': 0.008580823341236382, 'n_steps': 181.9906757748466, 'noptepochs': 19.321405513375872}.
[W 2019-06-14 19:18:15,197] Setting status of trial#0 as TrialState.FAIL because of the following error: ResourceExhaustedError()
Traceback (most recent call last):
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node loss/gradients/train_model/model/MatMul_236_grad/MatMul_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\optuna\study.py", line 399, in _run_trial
    result = func(trial)
  File "./optimize.py", line 90, in optimize_agent
    model.learn(evaluation_interval)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 369, in learn
    cliprange_vf=cliprange_vf_now))
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 297, in _train_step
    td_map)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node loss/gradients/train_model/model/MatMul_236_grad/MatMul_1 (defined at C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py:205) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'loss/gradients/train_model/model/MatMul_236_grad/MatMul_1', defined at:
  File "C:\Users\Nacho\Anaconda3\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Nacho\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Nacho\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\optuna\study.py", line 357, in func_child_thread
    self._run_trial(func, catch)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\optuna\study.py", line 399, in _run_trial
    result = func(trial)
  File "./optimize.py", line 83, in optimize_agent
    tensorboard_log=Path("./tensorboard").name, **model_params)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 100, in __init__
    self.setup_model()
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 205, in setup_model
    grads = tf.gradients(loss, self.params)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 664, in gradients
    unconnected_gradients)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 420, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py", line 1132, in _MatMulGrad
    grad_b = gen_math_ops.mat_mul(a, grad, transpose_a=True)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5630, in mat_mul
    name=name)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'train_model/model/MatMul_236', defined at:
  File "C:\Users\Nacho\Anaconda3\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
[elided 6 identical lines from previous traceback]
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 100, in __init__
    self.setup_model()
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 138, in setup_model
    reuse=True, **self.policy_kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\policies.py", line 701, in __init__
    layer_norm=True, feature_extraction="mlp", **_kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\policies.py", line 427, in __init__
    layer_norm=layer_norm)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\a2c\utils.py", line 231, in lstm
    + _ln(tf.matmul(hidden, weight_h), gain_h, bias_h) + bias
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2455, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5630, in mat_mul
    name=name)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[64,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node loss/gradients/train_model/model/MatMul_236_grad/MatMul_1 (defined at C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py:205) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by nachovoss** [comment]
I think there is running out of ram?? it seems to be building up ram usage as the program runs

**Comment by TalhaAsmal** [comment]
Can you please post your system specifications:

- CPU manufacturer and model
- RAM amount
- GPU manufacturer, model, and VRAM available (if applicable)

**Comment by nachovoss** [comment]
Hey TalhaAsmal! 
Thanks for your reply,

I was running it on an i5 7600 gtx1060 3gbVram
16gb ram
 Thanks in advance

**Comment by nachovoss** [comment]
I was looking arround online and it seems to be a Vram problem,  there is similar issues in other tensorflow projects. 
I kind of hack my way arround this by making a script that launches on a loop optimize.py  set tl n_jobs=1 , n_trails=10
