### ISSUE TITLE
Error during optimize.py

### ISSUE THREAD

**Issue by JakubSledz** [notadamking/Bitcoin-Trader-RL#71]
Optimize was running fine and after like 30min I got this message:
Traceback (most recent call last):
  File "./optimize.py", line 13, in <module>
    render_trained_model=True)
  File "D:\BTRL\lib\RLTrader.py", line 216, in train
    model.save(model_path)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 385, in save
    self._save_to_file(save_path, data=data, params=params)
  File "C:\Users\USER-KIN-00381\Anaconda3\envs\crypt\lib\site-packages\stable_baselines\common\base_class.py", line 346, in _save_to_file
    with open(save_path, "wb") as file_:
FileNotFoundError: [Errno 2] No such file or directory: 'data\\agents\\PPO2__MlpLnLstmPolicy__sortino__0.pkl

**Comment by georgeMuraveiAlkh** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data\agents\PPO2__MlpLnLstmPolicy__sortino__0.pkl 
It clearly says that you don't have "such file or directory". You should investigate deeper and create 'agents' folder.

**Comment by JakubSledz** [comment]
Ok but I believe this folder should be created by the script right?

**Comment by georgeMuraveiAlkh** [comment]
@notadamking added gitkeep to folder 'agents', to prevent this error. You are able to add this folder and check by your own. Or you may create few more issues in hope of getting help.
